apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
commonLabels:
  app.kubernetes.io/name: servercopilot
  app: servercopilot
configMapGenerator:
- name: servercopilot-base-config
  literals:
  - MQTT_BROKER_URL=${MQTT_BROKER_URL}
  - MQTT_USERNAME=${MQTT_USERNAME}
  - MQTT_PASSWORD=${MQTT_PASSWORD}