apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: staging
configMapGenerator:
  - name: servercopilot-base-config
    behavior: replace
    envs:
      - .env